import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import {GoogleOAuthProvider} from "@react-oauth/google"
const inter = Inter({ subsets: ["latin"] });
const quickSand=Quicksand({subsets:["latin"]})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="1057074883889-j1d1lkdsmoci2nth47hhbnirk2t03mt1.apps.googleusercontent.com">
      <body className={quickSand.className}>{children}</body>
      </GoogleOAuthProvider>
      
    </html>
  );
}
